version: "3.9"

services:
  apache:
    image: httpd:latest
    container_name: apache_container
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/local/apache2/htdocs/
    networks:
      - minha-rede
networks:
  minha-rede:
    driver: bridge
